### ISSUE TITLE
"Fetch" section

### ISSUE THREAD

**Issue by Vincent-M** [igrigorik/hpbn.co#1]
Hi,
Thanks a lot for this book!

The summary mentions the book will go through : _APIs available in the browser (XHR & **Fetch**, WebSocket, WebRTC, and more)_

I wasn't able to find the chapter about the Fetch api, is it a not yet released chapter due to the novelty of Fetch ?

**Comment by igrigorik** [comment]
I got ahead of myself on this one. When I was updating the description I was thinking I'd have time to add  a new chapter on Fetch API.. alas, that did not happen and I forgot to remove that from the description.

The good news is, it is the next thing on my list. Stay tuned.

In the meantime, removed it from the description in c93429a.

**Comment by Vincent-M** [comment]
That's awesome :) 
thanks!
