### ISSUE TITLE
CSS on index is broken

### ISSUE THREAD

**Issue by brunnerh** [igrigorik/hpbn.co#15]
The page links [`/assets/A.b708e9296b5e26f6bd725561648a1dda.css.pagespeed.cf.CoMduoQg_E.css`](https://hpbn.co/assets/A.b708e9296b5e26f6bd725561648a1dda.css.pagespeed.cf.CoMduoQg_E.css), which i get a 404 on.

![image](https://user-images.githubusercontent.com/834235/36311627-2db9d038-132c-11e8-8010-6dac87ded9e0.png)

**Comment by igrigorik** [comment]
Thanks for reporting this. There was a configuration bug on the server a few months back which triggered pagespeed module to run against hpbn.co. If you accessed the site at that time you would have picked up the asset links you're seeing above and the HTML was cached by the ServiceWorker on your device.. Now when you access it, those files are unavailable and hence the rendering behavior.

If you refresh the page once or twice (to force SW refresh), it should be fixed and shouldn't reappear. Can you give it a try?

**Comment by brunnerh** [comment]
It works as expected. Sorry for the late reply.

**Comment by igrigorik** [comment]
Glad to hear!
