### ISSUE TITLE
[WiFi]: Does WiFi retransmit UDP packets?

### ISSUE THREAD

**Issue by delthas** [igrigorik/hpbn.co#21]
Great book!

> The data and physical layer implementations of all WiFi protocols have their own retransmission and error correction mechanisms, which hide these wireless collisions from higher layers of the networking stack. 

> If your application is latency sensitive, then you may need to think carefully about adapting its behavior when running over a WiFi network. In fact, this may be a good reason to consider WebRTC, which offers the option of an unreliable UDP transport. Of course, switching transports won’t fix the radio network, but it can help lower the protocol and application induced latency overhead.

Does WiFi retransmit UDP packets that are lost or errored due to wireless collisions, or does it drop them?

**Comment by igrigorik** [comment]
WiFi transport does not care, or know even, what's inside the packets it shuttles between access points. In that way, yes, it does retransmit if there are collisions. The key bit here is that this is protocol independent and point-to-point, not end-to-end semantics.

**Comment by delthas** [comment]
Interesting, thanks for clarifying. I was wondering if it would somehow look at the IP packets' protocol field to differentiate between TCP and UDP and only try to retransmit TCP. I agree it would not make much sense, given it's lower down the protocol stack, but I find it interesting that in the end, you still get the retransmission & error correction & possibly some kind of HOL blocking for UDP datagrams over a wireless point-to-point link. So, it does make sense, but it's kinda counter-intuitive to what we're used to reading about UDP end-to-end semantics!
