### ISSUE TITLE
[Building Blocks of TCP]: Update information about TCP fast open

### ISSUE THREAD

**Issue by SuperOleg39** [igrigorik/hpbn.co#23]
Hello!

Really love your book, and first want to say big thanks for it :)

What do you think about current Fast Open state?

After reading https://squeeze.isobar.com/2019/04/11/the-sad-story-of-tcp-fast-open/ article, i found that Chrome no more use this feature.

Maybe need to update TCP article, and exclude Fast Open from recommendations?

**Comment by igrigorik** [comment]
Indeed, it's been quite the saga for TFO. That said, I think the original recommendation still stands:

> Allows application data to be sent in the initial SYN packet in certain situations. TFO is a new optimization, which requires support both on client and server; investigate if your application can make use of it.

To your point, unfortunately, it hasn't panned out in the browser but it's still a feature you get for "free" by running a recent kernel, and one that may benefit some applications that are able to make use of it.

**Comment by SuperOleg39** [comment]
You right, "sad story" article has example, where this option is valuable for DNS resolve)

Thanks!
