### ISSUE TITLE
[Primer on Latency and Bandwidth]: ...

### ISSUE THREAD

**Issue by joemorton** [igrigorik/hpbn.co#4]
The table at https://hpbn.co/primer-on-latency-and-bandwidth/#speed-of-light-and-propagation-has the same time for both one way (Time, light in fiber) and Round-trip time (RTT) in fiber for the Equatorial circumference. Should that be 200ms and 400ms respectively?

**Comment by igrigorik** [comment]
No, because the trip around the equator lands you at the same spot where you started.. in 200ms :-)

Thanks for the feedback!
