### ISSUE TITLE
[Transport Layer Security (TLS)]: ...

### ISSUE THREAD

**Issue by pmurphree** [igrigorik/hpbn.co#8]
I believe there is an error in the following section:

Since then, the IETF has continued iterating on the protocol to address security flaws, as well as to extend its capabilities: TLS 1.1 (RFC 2246) was published in April 2006, TLS 1.2 (RFC 5246) in August 2008, and work is now underway to define TLS 1.3.

TLS 1.1 is not RFC 2246, it is RFC 4346

**Comment by ElijahLynn** [comment]
Good catch, RFC 2246 is TLS 1.0 from 1999.

**Comment by igrigorik** [comment]
Sorry guys, missed this earlier! Great catch, it should indeed be pointing to [rfc4346.txt](https://www.ietf.org/rfc/rfc4346.txt) instead.
