### ISSUE TITLE
RTT in Latency Chapter

### ISSUE THREAD

**Issue by worenga** [igrigorik/hpbn.co#9]
https://github.com/igrigorik/hpbn.co/blob/fc2f6b79e50d6d69bc45a0879a86dc87f07f4465/primer-on-latency-and-bandwidth/index.html#L364

This should be 400ms shouldnt it?

**Comment by igrigorik** [comment]
No, because if you wrap a cable around the globe.. the snake just ate it's tail and the packet is back where it started. :-)
